services:
  erpbarczok_db:
    image: localhost/erpbarczok/erpbarczok_db:latest
    ports: 
      - 8083:5432
    container_name: test_db
    build: ../postgres
    environment:
      POSTGRES_PASSWORD: 'blablubber'