services:
  erpbarczok_db:
    image: localhost/erpbarczok/erpbarczok_db:latest
    ports: 
      - 8083:5432
    container_name: test_db
    build: ../postgres
    environment:
      POSTGRES_PASSWORD: 'blablubber'
    volumes:
      - /var/lib/postgresql/data
    healthcheck:
      test: psql -lqt -U postgres | cut -d | -f 1 | grep erpbarczok_db | echo $?
      start_period: 20s