services:
  erpbarczok-e2e:
    image: localhost/erpbarczok/erpbarczok:latest
    ports:
      - 8080:8080
    environment:
      NODE_ENV: 'development'
      DB_NAME: 'postgres'
      DB_USER: 'postgres'
      DB_PASSWORD: 'blablubber'
      DB_HOST: 'db'
      DB_PORT: 5432
      CLIENT_ID: 'CHzm5u0oVYPYlIbY6JinPgQG2ll9kG3t'
      CLIENT_ID_SWAGGER: '3W7Vgv8JOJSe1UoxtsxXLmwqBBiWgDZf'
      IDP_SERVER: 'https://dev-xny0abm7nsusygw7.eu.auth0.com/'
      AUDIENCE: 'http://localhost:8080'
      SCOPE: 'openid email profile admin user'
      PERMISSION_CLAIM: 'permissions'
    networks:
      - erpbarczok_net
    depends_on: 
      - db


  db:
    image: postgres:17.2-alpine3.20
    container_name: db
    environment:
      POSTGRES_PASSWORD: 'blablubber'
      POSTGRES_USER: 'postgres'
    networks:
      - erpbarczok_net

networks:
  erpbarczok_net:
    name: erpbarczok_net.internal
    driver: bridge