import { merge } from 'webpack-merge'
import common from './webpack.common.js'
import WorkboxPlugin from 'workbox-webpack-plugin'
import CopyPlugin from 'copy-webpack-plugin'

const config = merge(common, {
    mode: 'production',
    devtool: 'source-map',
    plugins: [
        new CopyPlugin({
            patterns: [
                {
                    // copy everything from src public to build destination directory
                    // https://stackoverflow.com/questions/44232366/how-do-i-build-a-json-file-with-webpack
                    from: "client/public",
                    to: "server/public",
                    globOptions: {
                        // will be generated by HtmlWebpackPlugin in webpack.common.js
                        // and must not be copied to not run into file conflicts
                        ignore: ["**/index.html"],
                    }
                }
            ]
        }),
        // generat Service Worker
        // https://webpack.js.org/guides/progressive-web-application/
        new WorkboxPlugin.GenerateSW({
            clientsClaim: true,
            skipWaiting: true
        })
    ]
})

export default config