services:
  erpbarczok:
    container_name: erpbarczok_kc
    image: erpbarczok_kc:latest
    build: ..
    ports: 
    - 8081:8080
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: "admin"
      KC_BOOTSTRAP_ADMIN_PASSWORD: "admin"
    volumes:
      - type: volume
        source: keycloak
        target: /opt/keycloak/data
        read_only: false
      - type: bind
        source: ../keycloak_realm
        target: /opt/keycloak/data/import
        read_only: false

volumes: 
  keycloak:
