name: GitHub Actions Demo
run-name: Create Docker Image for Project
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write
        attestations: write
        id-token: write
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
        - name: Check out repository code
          uses: actions/checkout@v4
        - name: Log in to registry
          run: echo "$GITHUB_TOKEN" | docker login ghcr.io -u "$GITHUB_ACTOR" --password-stdin
        - name: Start test db
          run: npm run starttestdb
          # builder for multiplatform from https://www.docker.com/blog/how-to-rapidly-build-multi-architecture-images-with-buildx/
        - name: Create Docker Image and Push Docker Image
          run: docker buildx create --name mybuilder --use --bootstrap && docker buildx build --push -t ghcr.io/rpbarczok/erpbarczok:latest --network host .
        - name: Stop test db
          run: npm run stoptestdb